### ISSUE TITLE
tmux 2.7 hangs on attach after 7+ days of uptime

### ISSUE THREAD

**Issue by sunaku** [tmux/tmux#1432]
Hello,

After 7+ days of uptime, sometimes `tmux attach -d` hangs indefinitely. 🤔 This has happened to me only thrice so far---but this time I issued the Control+4 shortcut to cause the binary to dump its core (as follows).

As the contribution guide suggests, I'm currently trying to reproduce the problem with tmux master at commit 33f9b316a356f72b8cf0fcd8ec25d415290ed588. I will report back in a week if successful. 😅  Until then, the backtrace below might be of use. 😇 

Thanks for your consideration.

```sh
$ uname -sp && tmux -V && echo $TERM
Linux unknown
tmux 2.7
xterm-256color

$ gdb `which tmux` core.26190
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/utils/tmux-2.7/bin/tmux...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New Thread 26190]
Missing separate debuginfo for /lib64/ld-linux-x86-64.so.2
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/79/d2286e5ebe0365ee41976078a9e9dc1b5fbee1
Missing separate debuginfo for
Try: yum --enablerepo='*-debug*' install /usr/lib/debug/.build-id/79/d2286e5ebe0365ee41976078a9e9dc1b5fbee1
Reading symbols from /lib64/libutil.so.1...Reading symbols from /usr/lib/debug/lib64/libutil-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libutil.so.1
Reading symbols from /home/utils/ncurses-5.9-shared/lib/libtinfo.so.5...(no debugging symbols found)...done.
Loaded symbols for /home/utils/ncurses-5.9-shared/lib/libtinfo.so.5
Reading symbols from /home/utils/libevent-2.0.22-stable/lib/libevent-2.0.so.5...done.
Loaded symbols for /home/utils/libevent-2.0.22-stable/lib/libevent-2.0.so.5
Reading symbols from /lib64/librt.so.1...Reading symbols from /usr/lib/debug/lib64/librt-2.12.so.debug...done.
done.
Loaded symbols for /lib64/librt.so.1
Reading symbols from /lib64/libresolv.so.2...Reading symbols from /usr/lib/debug/lib64/libresolv-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /lib64/libc.so.6...Reading symbols from /usr/lib/debug/lib64/libc-2.12.so.debug...done.
done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/libpthread.so.0...Reading symbols from /usr/lib/debug/lib64/libpthread-2.12.so.debug...done.
[Thread debugging using libthread_db enabled]
done.
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/lib64/ld-2.12.so.debug...done.
done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
Core was generated by `tmux attach -d'.
Program terminated with signal 3, Quit.
#0  0x00007ffff7090248 in __poll (fds=0x68b080, nfds=2, timeout=<value optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:83
83          return INLINE_SYSCALL (poll, 3, CHECK_N (fds, nfds), nfds, timeout);
(gdb) backtrace full
#0  0x00007ffff7090248 in __poll (fds=0x68b080, nfds=2, timeout=<value optimized out>) at ../sysdeps/unix/sysv/linux/poll.c:83
        resultvar = 18446744073709551100
        oldtype = <value optimized out>
        result = <value optimized out>
#1  0x00007ffff77898fa in poll_dispatch (base=0x68a5b0, tv=0x0) at poll.c:165
        res = <value optimized out>
        i = <value optimized out>
        j = <value optimized out>
        nfds = 2
        msec = -516
        pop = <value optimized out>
        event_set = 0x68b080
#2  0x00007ffff77787f8 in event_base_loop (base=0x68a5b0, flags=1) at event.c:1625
        evsel = 0x7ffff79a8660
        tv = {tv_sec = 16, tv_usec = 140737351981525}
        tv_p = 0x0
        res = <value optimized out>
        retval = <value optimized out>
        __func__ = "event_base_loop"
#3  0x000000000042f9da in proc_loop ()
No symbol table info available.
#4  0x0000000000406b6b in client_main ()
No symbol table info available.
#5  0x0000000000440eda in main ()
No symbol table info available.
(gdb) quit
```

**Comment by craigbarnes** [comment]
Did you update the kernel or system libraries in those 7 days?

**Comment by nicm** [comment]
No?

**Comment by nicm** [comment]
If you can still reproduce, try attaching strace to it and see what it is doing, this backtrace is just in the normal event loop there is nothing funny in it...

**Comment by nicm** [comment]
It could be the client hanging or the server, hard to tell.

**Comment by sunaku** [comment]
Sorry for the late response.  The machine did not undergo any kernel or software updates of any kind.  I will try attaching strace if it happens again (I'm currently running tmux master: I may have to downgrade back to 2.7 to help reproduce the bug).

**Comment by nicm** [comment]
Don't bother trying with 2.7, let me know if you can reproduce with master. It is probably the ba31d3a88c8c76ec3c76d9a91373fa24e64797cd bug.
