### ISSUE TITLE
SIGSEGV at window_update_focus(c->session->curw->window);

### ISSUE THREAD

**Issue by BenSYZ** [tmux/tmux#3932]
* tmux version: tmux 3.4
* Platform: Linux kenexs-arch 6.6.25-1-lts
* $TERM: tmux-256color

coredump stack:

```gdb
Program terminated with signal SIGSEGV, Segmentation fault.
#0  tty_keys_next (tty=tty@entry=0x63b32694cbb8) at /usr/src/debug/tmux/tmux/tty-keys.c:859
859                     window_update_focus(c->session->curw->window);
(gdb) bt
#0  tty_keys_next (tty=tty@entry=0x63b32694cbb8) at /usr/src/debug/tmux/tmux/tty-keys.c:859
#1  0x000063b31fc51a28 in tty_read_callback (fd=<optimized out>, events=<optimized out>, data=0x63b32694cbb8) at /usr/src/debug/tmux/tmux/tty.c:184
#2  0x000072584fe03c35 in event_persist_closure (ev=<optimized out>, base=0x63b31fdf7d60) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1623
#3  event_process_active_single_queue (base=base@entry=0x63b31fdf7d60, activeq=0x63b31fdf8030, max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1682
#4  0x000072584fe0539f in event_process_active (base=0x63b31fdf7d60) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1783
#5  event_base_loop (base=0x63b31fdf7d60, flags=flags@entry=1) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:2006
#6  0x000072584fe05696 in event_loop (flags=flags@entry=1) at /usr/src/debug/libevent/libevent-2.1.12-stable/event.c:1919
#7  0x000063b31fc41434 in proc_loop (loopcb=<optimized out>, tp=0x63b31fdf8e90) at /usr/src/debug/tmux/tmux/proc.c:217
#8  server_start (client=<optimized out>, flags=402718720, base=<optimized out>, lockfd=5, lockfile=0x63b31fdf8e60 "") at /usr/src/debug/tmux/tmux/server.c:252
#9  0x000063b31fbd67c9 in client_connect (flags=402718720, path=0x63b31fdf7b20 "/tmp/tmux-1000/default", base=0x63b31fdf7d60) at /usr/src/debug/tmux/tmux/client.c:164
#10 client_main (feat=0, flags=<optimized out>, argv=<optimized out>, argc=0, base=0x63b31fdf7d60) at /usr/src/debug/tmux/tmux/client.c:290
#11 main (argc=0, argv=<optimized out>) at /usr/src/debug/tmux/tmux/tmux.c:519
```

Sorry for not finding a reproduce path. It happens when I use it normally. But all I can remember is that:
1. Tmux continuously run for three days
2. what I've done, the problem have happen two times:
     1. crash when I ssh from termux with my phone to pc and then attach the existing session on pc.
     2. crash when I use it locally on my PC. I had attached from my phone like that in step 1, but I have already detached for a long time when it crash.

**Comment by nicm** [comment]
Does this still happen with master? It sounds like this may be fixed by 424f13fe13036e75b1c80e7751b81529f4cd8e15.

**Comment by BenSYZ** [comment]
As I do not have reproduce path, and considering it does not show up again, close it.
