### ISSUE TITLE
occasional crash from command input

### ISSUE THREAD

**Issue by shiroyagi** [tmux/tmux#3970]
### Issue description

Entering incorrect command sequence by mistake can crash tmux.  I can't repeat this reliably but manage to do it several times a month.  Possibly related to #3591 or #3952?  If there is insufficient information here (and you don't want to wait several weeks for me to reproduce and get the log files) then just close it.

### Required information

* tmux version (`tmux -V`) `3.2a`
* Platform (`uname -sp`) `Linux x86_64` (Ubuntu 22.04.4 LTS)
* $TERM inside and outside of tmux (`echo $TERM`) `screen` `xterm-kitty
`
Backtrace from core file:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=130485198268224) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=130485198268224) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=130485198268224, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x000076acf3c42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x000076acf3c287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000076acf3c89676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x76acf3ddbb77 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x000076acf3ca0cfc in malloc_printerr (str=str@entry=0x76acf3dd9809 "realloc(): invalid old size") at ./malloc/malloc.c:5664
#7  0x000076acf3ca4c6c in _int_realloc (av=av@entry=0x76acf3e1ac80 <main_arena>, oldp=oldp@entry=0x63c81e9ebc10, oldsize=oldsize@entry=109711157008656,
    nb=nb@entry=64) at ./malloc/malloc.c:4831
#8  0x000076acf3ca5909 in __GI___libc_realloc (oldmem=0x63c81e9ebc20, bytes=bytes@entry=48) at ./malloc/malloc.c:3485
#9  0x000076acf3ca79d4 in __GI___libc_reallocarray (optr=<optimised out>, nmemb=nmemb@entry=2, elem_size=elem_size@entry=24) at ./malloc/reallocarray.c:32
#10 0x000063c81c8d7370 in xreallocarray (ptr=<optimised out>, nmemb=2, size=24) at ./xmalloc.c:67
#11 0x000063c81c8b0a63 in status_prompt_key (key=<optimised out>, c=0x63c81e9dbfe0) at ./status.c:1310
#12 server_client_handle_key (c=0x63c81e9dbfe0, event=<optimised out>) at ./server-client.c:1364
#13 0x000063c81c8c4ced in tty_keys_next (tty=tty@entry=0x63c81e9dc110) at ./tty-keys.c:833
#14 0x000063c81c8c5a48 in tty_read_callback (fd=<optimised out>, events=<optimised out>, data=0x63c81e9dc110) at ./tty.c:171
#15 0x000076acf3f5ffd8 in event_persist_closure (ev=<optimised out>, base=0x63c81e7ec9a0) at /build/libevent-aonuXH/libevent-2.1.12-stable/event.c:1623
#16 event_process_active_single_queue (base=base@entry=0x63c81e7ec9a0, activeq=0x63c81e7ecc70, max_to_process=max_to_process@entry=2147483647,
    endtime=endtime@entry=0x0) at /build/libevent-aonuXH/libevent-2.1.12-stable/event.c:1682
#17 0x000076acf3f61bf7 in event_process_active (base=0x63c81e7ec9a0) at /build/libevent-aonuXH/libevent-2.1.12-stable/event.c:1783
#18 event_base_loop (base=0x63c81e7ec9a0, flags=flags@entry=1) at /build/libevent-aonuXH/libevent-2.1.12-stable/event.c:2006
#19 0x000076acf3f61e65 in event_loop (flags=flags@entry=1) at /build/libevent-aonuXH/libevent-2.1.12-stable/event.c:1919
#20 0x000063c81c85619f in proc_loop (loopcb=0x63c81c8b6c70 <server_loop>, tp=0x63c81e7edb70) at ./proc.c:220
#21 server_start (lockfile=<optimised out>, lockfd=<optimised out>, base=0x63c81e7ec9a0, flags=402718720, client=<optimised out>) at ./server.c:243
#22 client_connect (flags=<optimised out>, path=<optimised out>, base=0x63c81e7ec9a0) at ./client.c:164
#23 client_main (feat=0, flags=<optimised out>, argv=<optimised out>, argc=0, base=0x63c81e7ec9a0) at ./client.c:283
#24 main (argc=0, argv=<optimised out>) at ./tmux.c:518
```

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by nicm** [comment]
There was a crash when you delete from the command prompt which looked like this but I can't find when it was fixed. Please try with 3.4 or master and come back if you still see the issue.
