### ISSUE TITLE
if-shell causes segfault

### ISSUE THREAD

**Issue by tweekmonster** [tmux/tmux#872]
Compiled from 21240c1a8f89a4615b5bd8fa129618fb45c1c3cb.  It crashes immediately when `if-shell` is present in the configs.

```
Linux x86_64
tmux master
xterm-256color
```
Logs:

[tmux-client-28068.log.txt](https://github.com/tmux/tmux/files/948692/tmux-client-28068.log.txt)
[tmux-server-28070.log.txt](https://github.com/tmux/tmux/files/948693/tmux-server-28070.log.txt)

Minimal `tmux.conf`:

```
if-shell 'test -f ./tmux.conf' 'touch ./success.txt'
```

Ran with:

```
tmux -vvvv -Ltest -f./tmux.conf new
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tmux -vvvv -Ltest -f./tmux.conf new'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  cmd_if_shell_exec (self=0x13c6220, item=0x13c6380) at cmd-if-shell.c:123
123		cdata->client->references++;
(gdb) bt full
#0  cmd_if_shell_exec (self=0x13c6220, item=0x13c6380) at cmd-if-shell.c:123
        args = 0x13b20f0
        shared = 0x13c6280
        cdata = 0x13aa870
        shellcmd = 0x138d590 "test -f ./tmux.conf"
        cmd = <optimized out>
        cause = 0x455f60 <cmd_if_shell_entry> "\t_E"
        cmdlist = <optimized out>
        new_item = <optimized out>
        c = <optimized out>
        s = 0x0
        wl = <optimized out>
        wp = <optimized out>
        cwd = 0x0
#1  0x000000000041077d in cmdq_fire_command (item=0x13c6380) at cmd-queue.c:214
        c = 0x0
        retval = <optimized out>
        fsp = <optimized out>
        flags = 0
        cmd = 0x13c6220
        name = <optimized out>
        fs = {flags = 0, current = 0x0, s = 0x0, wl = 0x0, w = 0x0, wp = 0x0, idx = -1}
#2  cmdq_next (c=c@entry=0x0) at cmd-queue.c:334
        item = 0x13c6380
        retval = <optimized out>
        items = 226
        number = 227
        __func__ = "cmdq_next"
#3  0x0000000000436897 in server_loop () at server.c:199
        c = <optimized out>
        items = <optimized out>
#4  0x000000000042d6d2 in proc_loop (tp=0x137cfc0, loopcb=loopcb@entry=0x436880 <server_loop>) at proc.c:218
No locals.
#5  0x0000000000436e06 in server_start (base=base@entry=0x1382830, lockfd=lockfd@entry=6, lockfile=0x1384730 "") at server.c:180
        pair = {7, 8}
        job = <optimized out>
#6  0x0000000000407ab2 in client_connect (start_server=<optimized out>, path=0x13825e0 "/tmp/tmux-1000/test", base=0x1382830) at client.c:159
        sa = {sun_family = 1, sun_path = "/tmp/tmux-1000/test", '\000' <repeats 88 times>}
        fd = 7
        locked = 1
        size = <optimized out>
        lockfd = 6
        lockfile = 0x1384730 ""
#7  client_main (base=0x1382830, argc=argc@entry=1, argv=argv@entry=0x7ffd989f4578, flags=flags@entry=65536, shellcmd=shellcmd@entry=0x0)
    at client.c:267
        cmd = <optimized out>
        cmdlist = <optimized out>
        data = <optimized out>
        cmdflags = <optimized out>
        i = <optimized out>
        ttynam = <optimized out>
        cwd = <optimized out>
        ppid = <optimized out>
        msg = MSG_COMMAND
        cause = 0x0
        path = '\000' <repeats 1568 times>...
        tio = {c_iflag = 0, c_oflag = 0, c_cflag = 0, c_lflag = 0, c_line = 0 '\000', c_cc = '\000' <repeats 31 times>, c_ispeed = 0,
          c_ospeed = 0}
        saved_tio = {c_iflag = 1949237249, c_oflag = 1949266029, c_cflag = 762869101, c_lflag = 808464433, c_line = 47 '/',
          c_cc = "test", '\000' <repeats 27 times>, c_ispeed = 0, c_ospeed = 0}
        size = <optimized out>
#8  0x000000000040428e in main (argc=1, argv=0x7ffd989f4578) at tmux.c:350
        path = 0x13825e0 "/tmp/tmux-1000/test"
        label = 0x137b040 "EVENT_NOEPOLL=1"
        tmp = "/tmp", '\000' <repeats 4091 times>
        shellcmd = 0x0
        var = <optimized out>
        s = <optimized out>
        opt = <optimized out>
        flags = 65536
        keys = <optimized out>
        oe = <optimized out>
```

**Comment by nicm** [comment]
This should be fixed soon.

**Comment by nicm** [comment]
Should be fixed now. Thanks
